### PR TITLE
created skeleton for settings page

### PR DESCRIPTION
**Pull request by throwExceptionPlease**

### CODE REVIEW

**Comment by throwExceptionPlease** [comment]
Last push:
- Created folder to group settings.tsx and css file. 
- Added "gradYear" field in user type
- Used updateAccount() function to update the fields in the user doc.
- Disabled input fields until "Edit" button is clicked.
- PUT request when saving changes

**Review by ukataria — COMMENTED** [review]
Necessary changes on Slack

**Comment by throwExceptionPlease** [comment]
Updates:
Added guardian fields with the assumption that the user will have max 2 guardians. 
Added additional user fields such as address properties, yearsWithSwaliga, etc.
The amount of code here is **extremely heavy**. I tried to reduce it by using keys to map the properties and furthermore with the guardians' properties, but it led to some complications (i.e., type issues)--either way, would have required a lot of useState if we wanted to update the fields individually as they are being updated. With this, I tried to take the shortcut and do something like this:

```
async function handleGuardianInputChange(event, index, param) {
const userData = userDoc.data() as User;
 updatedGuardians[index][param] = event.target.value;

const updatedUserData = {
        ...userData,
        guardian: updatedGuardians,
      };
updateAccount(id, updatedUserData);
.
.
.
}

{currUser?.guardian.map((guardian, index) => (
  <div key={index}>
    <div className={styles.headerContainer}>
      <h2 className={styles.sectionHeader}>
        {`Emergency Contact #${index + 1} Information`}
      </h2>
      <hr id="hr" />
    </div>
    <div className={styles.settingField}>
      <input
        type="text"
        className={styles.inputContainer}
        value={''||guardian.firstName}
        onChange={(event) => handleGuardianInputChange(event, index, 'firstName')}
        disabled={disabled}
      />....

```
While this was mapped out fine, you couldn't get the inputs to render as you changed the fields.

**Comment by throwExceptionPlease** [comment]
- Verified data "fetch" and fields work with test data
- Rearranged logic such as having a single state object of User Type that represents each field of the user
- Haven't yet implemented the feature for adding/deleting guardians from their profile

**Review by nkanchinadam — APPROVED** [review]

**Pull request merged**
